name: CI
on:
  push:
    branch:
      - main
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: ./mvnw clean package