name: CI
on:
  push:
    branch:
      - main
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check Java version
        run: java -version
      - name: Build
        run: ./mvnw clean package